### ISSUE TITLE
NotImplementedError: Please use HDF reader for matlab v7.3 files

### ISSUE THREAD

**Issue by soichih** [yeatmanlab/AFQ-Browser#161]
Hello.

I am trying to run afqbrowser-assemble on my AFQ output (output.mat) and I am seeing following error message.

```
$ ~/git/AFQ-Browser/bin/afqbrowser-assemble output.mat 
Traceback (most recent call last):
  File "/N/u/brlife/Karst/git/AFQ-Browser/bin/afqbrowser-assemble", line 19, in <module>
    afqb.assemble(args.source, args.target)
  File "/N/u/brlife/Karst/.local/lib/python2.7/site-packages/afqbrowser/browser.py", line 150, in assemble
    out_path=op.join(site_dir, 'client', 'data'))
  File "/N/u/brlife/Karst/.local/lib/python2.7/site-packages/afqbrowser/browser.py", line 43, in mat2tables
    afq = sio.loadmat(mat_file_name, squeeze_me=True)['afq']
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 135, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 65, in mat_reader_factory
    raise NotImplementedError('Please use HDF reader for matlab v7.3 files')
NotImplementedError: Please use HDF reader for matlab v7.3 files
```

I am saving the AFQ output like following.

https://github.com/brain-life/app-tractclassification/blob/master/main.m#L66

```
save('output.mat','fg_classified','classification','-v7.3');    
```

I am not exactly sure why we are using "-v7.3" option to save it, but will it not work if I have it?

**Comment by arokem** [comment]
Might not. Scipy's mat-file reader only reads certain versions of mat files. This shouldn't be too hard to fix with something like h5py, and we should do that. It might take us a little while, though. I'm leaving this open for now, so that we remember to do that. 

For the time being, does it work for you if you don't save the mat file explicitly as v7.3? What version of Matlab are you working with?

**Comment by soichih** [comment]
We are *starting* to use 2017a, but I believe most of our apps still runs on 2016a.  I will find out we can start storing our AFQ output in HDF5 format.

**Comment by skjerns** [comment]
I've implemented a library that can read the `mat 7.3` files, have a look here:

[mat 7.3](https://github.com/skjerns/mat7.3)

or install via pip `pip install mat73` and load with

```Python
import mat73
data_dict = mat73.loadmat('data.mat')
```

**Comment by arokem** [comment]
That is cool! Have you considered contributing this upstream to scipy?

**Comment by skjerns** [comment]
Mhh, I'll consider it. 

However, it introduces a dependency on `h5py`, not sure how happy they would be about that.

**Comment by siri-ius** [comment]
> 
> 
> I've implemented a library that can read the `mat 7.3` files, have a look here:
> 
> [mat 7.3](https://github.com/skjerns/mat7.3)
> 
> or install via pip `pip install mat73` and load with
> 
> ```python
> import mat73
> data_dict = mat73.loadmat('data.mat')
> ```

this worked for me

**Comment by NYcleaner** [comment]
#if  matlab save data use  ‘-v7.3’，scipy.io.loadmat api load may lead mistake ，thus can use like：

```
import h5py
f = h5py.File('http.mat', 'r')
print(f.keys()) # <KeysViewHDF5 ['X', 'y']>  
print(f['X'][:])

**Comment by ghost** [comment]
> I've implemented a library that can read the `mat 7.3` files, have a look here:

It worked for me, thanks
